"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

from math import sqrt
from math import ceil

SCALE = 500

def num_divisors(n):
    rangecap = 0
    if ceil(sqrt(n)) == sqrt(n):
        rangecap = int(ceil(sqrt(n))+1)
    else:
        rangecap = int(ceil(sqrt(n)))
        
    total = 0
#    print str(n)+':',
    for i in range(1, rangecap):
        if n%i==0:
#            print str(i), 
#            if i*i!=n:
#                print str(n/i),
            total += 2
        if i*i==n:
            total -= 1
#    print '\n'
    return total

tri = 0
counter = 1
divisors = 0

while divisors<SCALE:
    tri += counter
    counter += 1
    divisors = num_divisors(tri)
    
print tri
